export const HOME_ROUTE = '/'
export const NOT_FOUND = '*'
export const ABOUT_ROUTE = '/aboutUs'
export const CARD_ROUTE = '/catalog'
export const OBJECTS_ROUTE = '/ourobjects'
export const SERVICES_ROUTE = '/ourservices'